### ISSUE TITLE
Compiling problem when updating SDK to 35

### ISSUE THREAD

**Issue by gmemicarra** [YoYoGames/GMEXT-GooglePlayServices#22]
### Description

To anyone having problem compiling:
After compiling Google's SDK to lvl 35, and GMS2 to 2024.13.1.193, it fails to compile throwing these errors:

`\YYGooglePlayServices.java:50: error: cannot find symbol
import com.google.android.gms.games.Games;

YYGooglePlayServices.java:86: error: cannot find symbol
import com.google.android.gms.drive.Drive;
                                   ^
  symbol:   class Drive
  location: package com.google.android.gms.drive
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors`

**To fix this**, go to the extension folder, open YYGooglePlayServices.java, and comment:
`import com.google.android.gms.games.Games;
import com.google.android.gms.drive.Drive;`

### Sample Package

-

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.13.1.193

### Which platform(s) are you seeing the problem on?

Android
